### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by robertfausk** [symfony2admingenerator/GeneratorBundle#151]
Will there be a roadmap?
When will this project be stable?
What about upgrade notes from old-legacy version? 
Will an upgrade be possible at all?

**Comment by loostro** [comment]
@robertfausk 

1. Issue #38 contains major TODO points. Also see issues list (there are not that many) for an overview what needs to be done.
2. The team has 2 active maintainers and we have a few active users. Since we're doing this in our part-time there is no timeframe. I was planning to go for stable release soon, but recently I started a new job, and it seems I won't have any extra time soon.
3. The major stable release blocking points are: documentation and tests.
4. No. Well, in theory yes, you could upgrade. But we've refactored some internals and switched to a completely diffrent theme (all templates have changed), form and filters handleing has changed... if you had any customizations - you'd have to adjust them. I can imagine that for a middle-sized project the amount of manhours spent on upgrade would not pay off. You'd probably be better off starting from a new (clean) project copying models and customizing again.
