### ISSUE TITLE
Indefinido indice : Access

### ISSUE THREAD

**Issue by atamashi** [symfony2admingenerator/GeneratorBundle#208]
Estoy trabajando con windows 7 y php 5.5.28. He instalado y configurado el paquete  y todos sus requerimientos. Pero cuando lo corro en localhost ni siquiera carga, no alcanza a crear logs, y me arroja este mensaje: 
Symfony\Component\Debug\Exception\ContextErrorException
Notice:Undefined index: access
En mi AppBundle no uso ese termino como indice. Buscando con sublimetext encontre que en el paquete symfony2admingenerator/GeneratorBundle y sus requeridos Bundles, si se usa. Gracias.
Mucha suerte con este proyecto y felicitaciones, es magnifico!

**Comment by javiereguiluz** [comment]
@atamashi this is a repository accessed by people from all around the world. That's why English is the only language used to communicate. Please don't add comments in Spanish. Thanks!

-----

*@atamashi a este repositorio accede gente de todo el mundo. Por eso solamente se usa el inglés para todas las comunicaciones. Por favor, no añadas comentarios en español. Gracias*

**Comment by atamashi** [comment]
ok, Im sorry!

**Comment by atamashi** [comment]
excuseme, please

**Comment by bobvandevijver** [comment]
You van reopen when you have an English translation :)
