### ISSUE TITLE
Date range in filter

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#216]
What's the easiest way to add a range type in filter for date fields?
This bundle has perhaps some build-in features?

Thanks

**Comment by bobvandevijver** [comment]
Our formextensionsbundle has a DateRange Picker, so you might be able to use that one: [daterange-picker](https://github.com/symfony2admingenerator/FormExtensionsBundle/blob/master/Resources/doc/daterange-picker/overview.md). I currently do not have use a daterange in a filter: it is although always possible to define extra fields and do the filtering manually. 

By the way, when I look at the implementation of the QueryFilter, I do see support to add from/to datatime filters: check the [DoctrineQueryFilter.php#L105](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/QueryFilter/DoctrineQueryFilter.php#L105). Not sure how to use that though, so if you find out, please post it here so that I can add it to the docs!

**Comment by Lionel09** [comment]
Thanks,

I've just updated the default filters type to use the FormExtension daterange type, it works.

```
    filter_types:
        propel:
            DATE:          s2a_daterange_picker
            BU_DATE:       s2a_daterange_picker
            TIMESTAMP:     s2a_daterange_picker 
            BU_TIMESTAMP:  s2a_daterange_picker 
```

**Comment by Lionel09** [comment]
the display works, but not the form validation, i have to look further in this one when i got time...

**Comment by Lionel09** [comment]
ok for propel

https://github.com/symfony2admingenerator/GeneratorBundle/pull/219
